apiVersion: apps/v1
kind: Deployment
metadata:
  name: marajoarafront-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marajoarafront
  template:
    metadata:
      labels:
        app: marajoarafront
    spec:
      containers:
      - name: marajoarafront
        image: rafaelpolmann/marajoara-front:latest
        ports:
        - containerPort: 80
          hostPort: 4400
