apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kube
  labels:
    type: pvc-kube
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  selector:
    matchLabels:
      type: pv-kube

