apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kube
  labels:
    type: pv-kube
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kubedata/
  storageClassName: manual