apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      volumes:
      - name: kubedata
        persistentVolumeClaim:
          claimName: pvc-kube
      containers:
      - name: sqlserver-kube
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "sql123!@#"
        volumeMounts:
        - name: kubedata
          mountPath: /var/opt/mssql/data
